nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: Number's Api Documentation
            description: 
            version: 3.0.1
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!(/doc|/doc.json)$)